name: Bug Report
description: Report a bug or unexpected behavior in 100xBot
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us identify and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Execute agent command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Tell us what you expected
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Tell us what actually happened
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Brave
        - Edge
        - Firefox
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser are you using?
      placeholder: e.g., 120.0.6099.109
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: 100xBot Version
      description: What version of 100xBot are you using? (Check in chrome://extensions)
      placeholder: e.g., 1.4.130
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (Ubuntu)
        - Linux (Other)
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: llm-provider
    attributes:
      label: LLM Provider
      description: Which LLM provider were you using when the bug occurred?
      options:
        - OpenAI
        - Anthropic (Claude)
        - Google (Gemini)
        - Groq
        - OpenRouter
        - Custom/Self-hosted
        - Not applicable
        - Other (please specify in additional context)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Errors
      description: Please copy and paste any relevant log output or error messages. Check the browser console (F12) and extension logs.
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: If applicable, add screenshots or videos to help explain the problem. You can drag and drop images here.
      placeholder: Drag and drop images here
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (e.g., specific websites, prompts used, configurations)
      placeholder: Any additional information that might help us understand the issue
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched for similar issues and couldn't find a duplicate
          required: true
        - label: I have checked the documentation and FAQ
          required: true
        - label: I have included all the relevant information above
          required: true
