name: Question / Support
description: Ask a question or get help with using 100xBot
title: "[Question]: "
labels: ["question", "support"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about 100xBot? We're here to help!

        **Note:** For bug reports, please use the Bug Report template instead.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation & Setup
        - Configuration
        - Agent Usage & Commands
        - LLM Integration
        - Browser Automation
        - Data Extraction
        - Troubleshooting
        - Best Practices
        - Use Cases & Examples
        - Performance & Optimization
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What do you need help with? Be as detailed as possible.
      placeholder: I'm trying to... but I'm not sure how to...
    validations:
      required: true

  - type: textarea
    id: what-tried
    attributes:
      label: What Have You Tried?
      description: Describe what you've already attempted
      placeholder: |
        1. I tried...
        2. I looked at...
        3. I expected... but got...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that might help us answer your question
      placeholder: |
        - Browser/OS: Chrome on macOS
        - 100xBot version: 1.4.130
        - What I'm trying to accomplish: ...
        - Relevant configurations: ...
    validations:
      required: false

  - type: textarea
    id: code-or-config
    attributes:
      label: Relevant Code or Configuration
      description: If applicable, share relevant code, configuration, or prompts
      render: yaml
      placeholder: |
        # Your configuration or code here
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your question
      placeholder: Drag and drop images here
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have checked the documentation
          required: true
        - label: This is a question, not a bug report or feature request
          required: true
